version: "2.0"
services:
  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:arm32v6
    container_name: zigbee2mqtt
    restart: always
    volumes:
    - ./zigbee2mqtt:/app/data/
    devices:
    - "/dev/ttyACM0"
  mosquitto:
      image: eclipse-mosquitto
      hostname: mosquitto
      container_name: mosquitto
      expose:
        - "1883"
        - "9001"
      ports:
        - "1883:1883"
        - "9001:9001"
      volumes:
      - ./mosquitto:/mosquitto/config/mosquitto
  nodered:
    image: raymondmm/node-red-homekit:1.0.0-0.20.0-10-alpine-arm32v6
    user: '0'
    privileged: true
    ports:
      - "1880:1880"
      - "51827:51827"
    volumes:
    - ./nodered:/data
  grafana:
    image: fg2it/grafana-armhf:v5.0.2
    container_name: grafana
    ports:
    - "3000:3000"
    volumes:
    - ./grafana:/var/lib/grafana
  influx:
    image: hypriot/rpi-influxdb
    container_name: influxdb
    volumes:
    - ./influxdb:/data
    environment:
    - PRE_CREATE_DB="home"
    - ADMIN_USER="root"
    - INFLUXDB_INIT_PWD="root"
